### ISSUE TITLE
USER STORY: Set up repository

### ISSUE THREAD

**Issue by laurakond** [laurakond/Stitch-Art-Guides#1]
EPIC: set up repo

As a **developer** I can **set up a new workspace** so that **I can start working on my project**

## Acceptance Criteria
* Acceptance Criteria 1: a repository in Github
* Acceptance Criteria 2: an IDE to work in
* Acceptance Criteria 3: a project board
* Acceptance Criteria 4: readme & testing files

## Tasks
- [x] Task 1: install Django
- [ ] Task 2: link to Code Institute database
- [ ] Task 3: deploy to Heroku
- [ ] Task 4: test deployment
